### ISSUE TITLE
[blank_react_project] "regeneratorRuntime is not defined" in production build

### ISSUE THREAD

**Issue by frol** [nearprotocol/create-near-app#91]
When I build `blank_react_project` for production deployment (`npm run build:web`), the produced output is broken for me in the latest Firefox and Chrome browsers - it just displays a blank page, and here is the DevTools console output:

```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

Here is how I fixed it: https://github.com/frol/near-hackathon-jankcity/commit/db5ccf2a6d60a65e2272ccb63e5d389441abd1e4 (I haven't quite understood the nature of the problem, so the solution might be suboptimal)

**Comment by vgrichina** [comment]
@frol I understand the nature of the problem, I think there is a fix for blank project but I forgot for React.

```
blank_project/src/main.js
1:import "regenerator-runtime/runtime";
```

It's basically happening because Babel re-compiles code using `async` / `await` to work on older browsers without support for this. But it's "regenerator" because generators appeared in JS before `async` / `await` and are powerful enough to replicate `async` / `await` behavior. So I assume babel compiles `async` / `await` to generators and then applies https://www.npmjs.com/package/regenerator which also ends up requiring this runtime stuff.

**Comment by vgrichina** [comment]
https://github.com/nearprotocol/create-near-app/commit/21d39a3f66de83fcb643b7e043a11894a2b1d31c
